services:
  app:
    build: .
    image: backend-app:v1.0
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=NOTEBOOK
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NOTEBOOK
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
